apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
localAPIEndpoint:
  advertiseAddress: 10.0.2.15
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: localhost.localdomain
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.18.0
clusterName: kubernetes
imageRepository: k8s.gcr.io
certificatesDir: /etc/kubernetes/pki
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
apiServer:
  timeoutForControlPlane: 4m0s
  extraArgs:
    authorization-mode: "Node,RBAC"
    # Disable API aggregator
    proxy-client-cert-file: ""
    proxy-client-key-file: ""
    requestheader-allowed-names: ""
    requestheader-client-ca-file: ""
controllerManager: 
  extraArgs:
    # Disable API aggregator
    requestheader-client-ca-file: ""
scheduler: {}
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
TLSCertFile: /etc/kubernetes/pki/kubelet-server.crt
TLSPrivateKeyFile: /etc/kubernetes/pki/kubelet-server.key
